/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CookProfileSchema extends BaseModel {
  static $columns = ['address', 'bio', 'city', 'createdAt', 'id', 'image', 'kitchenName', 'latitude', 'longitude', 'phone', 'updatedAt', 'userId', 'wallet'] as const
  $columns = CookProfileSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare bio: string | null
  @column()
  declare city: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare image: string | null
  @column()
  declare kitchenName: string | null
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare wallet: string
}

export class MealComponentSchema extends BaseModel {
  static $columns = ['createdAt', 'defaultQuantity', 'id', 'isToggle', 'maxQuantity', 'mealPlanId', 'name', 'price', 'updatedAt'] as const
  $columns = MealComponentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare defaultQuantity: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isToggle: boolean | null
  @column()
  declare maxQuantity: number | null
  @column()
  declare mealPlanId: string
  @column()
  declare name: string | null
  @column()
  declare price: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MealPlanSchema extends BaseModel {
  static $columns = ['availableDurations', 'bannerImage', 'basePrice', 'cookId', 'createdAt', 'description', 'id', 'isActive', 'subscriberLimit', 'title', 'updatedAt', 'validityType'] as const
  $columns = MealPlanSchema.$columns
  @column()
  declare availableDurations: any
  @column()
  declare bannerImage: string | null
  @column()
  declare basePrice: number
  @column()
  declare cookId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column()
  declare subscriberLimit: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare validityType: string
}

export class OrderNoteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'note', 'orderId', 'updatedAt', 'userId'] as const
  $columns = OrderNoteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare note: string | null
  @column()
  declare orderId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class OrderSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'orderDate', 'price', 'status', 'subscriptionId', 'totalPrice', 'updatedAt'] as const
  $columns = OrderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.date()
  declare orderDate: DateTime | null
  @column()
  declare price: number | null
  @column()
  declare status: string | null
  @column()
  declare subscriptionId: string
  @column()
  declare totalPrice: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PaymentSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'method', 'orderId', 'status', 'subscriptionId', 'type', 'updatedAt', 'userId'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare amount: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare method: string | null
  @column()
  declare orderId: string | null
  @column()
  declare status: string | null
  @column()
  declare subscriptionId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class PickupSlotSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'id', 'latitude', 'locationName', 'longitude', 'mealPlanId', 'pickupTime', 'updatedAt'] as const
  $columns = PickupSlotSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare latitude: string | null
  @column()
  declare locationName: string | null
  @column()
  declare longitude: string | null
  @column()
  declare mealPlanId: string
  @column()
  declare pickupTime: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReviewSchema extends BaseModel {
  static $columns = ['comment', 'cookId', 'createdAt', 'id', 'rating', 'updatedAt', 'userId'] as const
  $columns = ReviewSchema.$columns
  @column()
  declare comment: string | null
  @column()
  declare cookId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare rating: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class SubscribedMealComponentSchema extends BaseModel {
  static $columns = ['createdAt', 'enabled', 'id', 'mealComponentId', 'price', 'quantity', 'subscriptionId', 'updatedAt'] as const
  $columns = SubscribedMealComponentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare enabled: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mealComponentId: string
  @column()
  declare price: number | null
  @column()
  declare quantity: number | null
  @column()
  declare subscriptionId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SubscriptionSchema extends BaseModel {
  static $columns = ['amountConsumed', 'amountPaid', 'createdAt', 'duration', 'endDate', 'id', 'mealPlanId', 'pickupSlotId', 'startDate', 'status', 'totalPrice', 'updatedAt', 'userId'] as const
  $columns = SubscriptionSchema.$columns
  @column()
  declare amountConsumed: string
  @column()
  declare amountPaid: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare duration: string
  @column.date()
  declare endDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mealPlanId: string
  @column()
  declare pickupSlotId: string
  @column.date()
  declare startDate: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare totalPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'isActive', 'name', 'password', 'phone', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
